AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ThePai-Telegram-Bot-Serverless

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - x86_64

Resources:
  PaiFunctions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python/
      Handler: app.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess

Outputs:
  TelegramApi:
    Description: "Lambda URL for PTB function"
    Value:
      Fn::GetAtt: PaiFunctionsUrl.FunctionUrl
